# secrets.toml

# Alpaca API
APCA_API_KEY_ID = "PKEBQZUMI7U4TUKERROSY7K5MX"
APCA_API_SECRET_KEY = "9ZXtfkZiGnbkbAqyrueaNYoRfpWVQnNoQeZJqmQGBGhq"

# Financial Modeling Prep API Key
FMP_API_KEY = "YOUR_FMP_API_KEY_GOES_HERE"